### ISSUE TITLE
The date due edit for teachers is super buggy

### ISSUE THREAD

**Issue by broanlovespanda** [gregthegeek/JGrader#39]

**Comment by gregthegeek** [comment]
Can you elaborate on specific steps to reproduce the issue? It seems to work fine for me.

**Comment by broanlovespanda** [comment]
Try using safari? 50% of the time I change it it says switches to a bunch of nulls and Na

**Comment by broanlovespanda** [comment]
check the "submit stdin example here" assignment for an example

**Comment by gregthegeek** [comment]
Ya I successfully replicated the issue in Safari, I'll have to do some more debugging later.
