### ISSUE TITLE
Double Password Registration

### ISSUE THREAD

**Issue by broanlovespanda** [gregthegeek/JGrader#96]

**Comment by gregthegeek** [comment]
What is this? Like a confirm password field? I don't think we should have one.

**Comment by broanlovespanda** [comment]
Every website since the dawn of the Internet has a confirm password field.

**Comment by gregthegeek** [comment]
I don't like it.

**Comment by gregthegeek** [comment]
I just checked facebook, twitter, and github, and none have confirm password. I don't want to add another field that people have to fill out, and if they make a mistake they can just use the password recovery tool.

**Comment by broanlovespanda** [comment]
those websites are in the minority but we can leave it alone for now
